runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:7utOCXZxdhcin5tUKJUachQZ7ddP9ZWha5KB/hHRXw4=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
